# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import internal_pb2 as internal__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in soapstone_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SoapstoneStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerInfo = channel.unary_unary(
                '/SoapstoneLib.Proto.Internal.Soapstone/GetServerInfo',
                request_serializer=common__pb2.ServerInfoRequest.SerializeToString,
                response_deserializer=common__pb2.ServerInfoResponse.FromString,
                _registered_method=True)
        self.SearchObjects = channel.unary_unary(
                '/SoapstoneLib.Proto.Internal.Soapstone/SearchObjects',
                request_serializer=internal__pb2.SearchObjectsRequest.SerializeToString,
                response_deserializer=internal__pb2.SearchObjectsResponse.FromString,
                _registered_method=True)
        self.GetObject = channel.unary_unary(
                '/SoapstoneLib.Proto.Internal.Soapstone/GetObject',
                request_serializer=internal__pb2.GetObjectRequest.SerializeToString,
                response_deserializer=internal__pb2.GetObjectResponse.FromString,
                _registered_method=True)
        self.BatchGetObjects = channel.unary_unary(
                '/SoapstoneLib.Proto.Internal.Soapstone/BatchGetObjects',
                request_serializer=internal__pb2.BatchGetObjectsRequest.SerializeToString,
                response_deserializer=internal__pb2.BatchGetObjectsResponse.FromString,
                _registered_method=True)
        self.OpenResource = channel.unary_unary(
                '/SoapstoneLib.Proto.Internal.Soapstone/OpenResource',
                request_serializer=internal__pb2.OpenResourceRequest.SerializeToString,
                response_deserializer=internal__pb2.OpenResourceResponse.FromString,
                _registered_method=True)
        self.OpenObject = channel.unary_unary(
                '/SoapstoneLib.Proto.Internal.Soapstone/OpenObject',
                request_serializer=internal__pb2.OpenObjectRequest.SerializeToString,
                response_deserializer=internal__pb2.OpenObjectResponse.FromString,
                _registered_method=True)
        self.OpenSearch = channel.unary_unary(
                '/SoapstoneLib.Proto.Internal.Soapstone/OpenSearch',
                request_serializer=internal__pb2.OpenSearchRequest.SerializeToString,
                response_deserializer=internal__pb2.OpenSearchResponse.FromString,
                _registered_method=True)
        self.ExecuteMassEdit = channel.unary_unary(
                '/SoapstoneLib.Proto.Internal.Soapstone/ExecuteMassEdit',
                request_serializer=internal__pb2.ExecuteMassEditRequest.SerializeToString,
                response_deserializer=internal__pb2.ExecuteMassEditResponse.FromString,
                _registered_method=True)
        self.ReloadParams = channel.unary_unary(
                '/SoapstoneLib.Proto.Internal.Soapstone/ReloadParams',
                request_serializer=internal__pb2.ReloadParamsRequest.SerializeToString,
                response_deserializer=internal__pb2.ReloadParamsResponse.FromString,
                _registered_method=True)
        self.ListParams = channel.unary_unary(
                '/SoapstoneLib.Proto.Internal.Soapstone/ListParams',
                request_serializer=internal__pb2.ListParamsRequest.SerializeToString,
                response_deserializer=internal__pb2.ListParamsResponse.FromString,
                _registered_method=True)
        self.DescribeParam = channel.unary_unary(
                '/SoapstoneLib.Proto.Internal.Soapstone/DescribeParam',
                request_serializer=internal__pb2.DescribeParamRequest.SerializeToString,
                response_deserializer=internal__pb2.DescribeParamResponse.FromString,
                _registered_method=True)
        self.GetParamRow = channel.unary_unary(
                '/SoapstoneLib.Proto.Internal.Soapstone/GetParamRow',
                request_serializer=internal__pb2.GetParamRowRequest.SerializeToString,
                response_deserializer=internal__pb2.GetParamRowResponse.FromString,
                _registered_method=True)
        self.GetParamRows = channel.unary_unary(
                '/SoapstoneLib.Proto.Internal.Soapstone/GetParamRows',
                request_serializer=internal__pb2.GetParamRowsRequest.SerializeToString,
                response_deserializer=internal__pb2.GetParamRowsResponse.FromString,
                _registered_method=True)
        self.ListParamRows = channel.unary_unary(
                '/SoapstoneLib.Proto.Internal.Soapstone/ListParamRows',
                request_serializer=internal__pb2.ListParamRowsRequest.SerializeToString,
                response_deserializer=internal__pb2.ListParamRowsResponse.FromString,
                _registered_method=True)
        self.SetParamCell = channel.unary_unary(
                '/SoapstoneLib.Proto.Internal.Soapstone/SetParamCell',
                request_serializer=internal__pb2.SetParamCellRequest.SerializeToString,
                response_deserializer=internal__pb2.SetParamCellResponse.FromString,
                _registered_method=True)


class SoapstoneServicer:
    """Missing associated documentation comment in .proto file."""

    def GetServerInfo(self, request, context):
        """Returns basic info about the editor's current state. All servers must implement this.
        Editor resources are parts of an editor which can be individually loaded or unloaded.
        Once a resource is loaded, various objects and functionality can be straightforwardly accessed within it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchObjects(self, request, context):
        """Get objects matching a search query, with requested properties.
        A property does not have to be requested to search against it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObject(self, request, context):
        """Returns a single object, within an editor resource type.
        This can be used if the exact key is known, or to get more properties after a broader search.
        It returns empty if object is not found (as opposed to an error).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetObjects(self, request, context):
        """Returns objects in batch, within an editor resource type.
        It returns only the objects which could be found.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenResource(self, request, context):
        """Open a resource, like a map by name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenObject(self, request, context):
        """Jump to or frame the given object within the editor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenSearch(self, request, context):
        """Start a given search in the editor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteMassEdit(self, request, context):
        """Execute a mass edit script on the server's param data.
        The script uses the same syntax as the Param Editor's Mass Edit system.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadParams(self, request, context):
        """Hot-reload param changes to the running game process.
        If param_names is empty, all reloadable params are reloaded.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListParams(self, request, context):
        """List all available param names in the currently loaded project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeParam(self, request, context):
        """Get detailed information about a specific param: its type, row count, and field definitions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParamRow(self, request, context):
        """Get all field values for a specific row, by row index (position).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParamRows(self, request, context):
        """Get all rows that share a given row ID (handles duplicate IDs).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListParamRows(self, request, context):
        """List all rows in a param (ID, Name, and index summary).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetParamCell(self, request, context):
        """Set a single cell value by row index. Handles duplicate-ID params precisely.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SoapstoneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=common__pb2.ServerInfoRequest.FromString,
                    response_serializer=common__pb2.ServerInfoResponse.SerializeToString,
            ),
            'SearchObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchObjects,
                    request_deserializer=internal__pb2.SearchObjectsRequest.FromString,
                    response_serializer=internal__pb2.SearchObjectsResponse.SerializeToString,
            ),
            'GetObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObject,
                    request_deserializer=internal__pb2.GetObjectRequest.FromString,
                    response_serializer=internal__pb2.GetObjectResponse.SerializeToString,
            ),
            'BatchGetObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetObjects,
                    request_deserializer=internal__pb2.BatchGetObjectsRequest.FromString,
                    response_serializer=internal__pb2.BatchGetObjectsResponse.SerializeToString,
            ),
            'OpenResource': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenResource,
                    request_deserializer=internal__pb2.OpenResourceRequest.FromString,
                    response_serializer=internal__pb2.OpenResourceResponse.SerializeToString,
            ),
            'OpenObject': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenObject,
                    request_deserializer=internal__pb2.OpenObjectRequest.FromString,
                    response_serializer=internal__pb2.OpenObjectResponse.SerializeToString,
            ),
            'OpenSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSearch,
                    request_deserializer=internal__pb2.OpenSearchRequest.FromString,
                    response_serializer=internal__pb2.OpenSearchResponse.SerializeToString,
            ),
            'ExecuteMassEdit': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteMassEdit,
                    request_deserializer=internal__pb2.ExecuteMassEditRequest.FromString,
                    response_serializer=internal__pb2.ExecuteMassEditResponse.SerializeToString,
            ),
            'ReloadParams': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadParams,
                    request_deserializer=internal__pb2.ReloadParamsRequest.FromString,
                    response_serializer=internal__pb2.ReloadParamsResponse.SerializeToString,
            ),
            'ListParams': grpc.unary_unary_rpc_method_handler(
                    servicer.ListParams,
                    request_deserializer=internal__pb2.ListParamsRequest.FromString,
                    response_serializer=internal__pb2.ListParamsResponse.SerializeToString,
            ),
            'DescribeParam': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeParam,
                    request_deserializer=internal__pb2.DescribeParamRequest.FromString,
                    response_serializer=internal__pb2.DescribeParamResponse.SerializeToString,
            ),
            'GetParamRow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParamRow,
                    request_deserializer=internal__pb2.GetParamRowRequest.FromString,
                    response_serializer=internal__pb2.GetParamRowResponse.SerializeToString,
            ),
            'GetParamRows': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParamRows,
                    request_deserializer=internal__pb2.GetParamRowsRequest.FromString,
                    response_serializer=internal__pb2.GetParamRowsResponse.SerializeToString,
            ),
            'ListParamRows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListParamRows,
                    request_deserializer=internal__pb2.ListParamRowsRequest.FromString,
                    response_serializer=internal__pb2.ListParamRowsResponse.SerializeToString,
            ),
            'SetParamCell': grpc.unary_unary_rpc_method_handler(
                    servicer.SetParamCell,
                    request_deserializer=internal__pb2.SetParamCellRequest.FromString,
                    response_serializer=internal__pb2.SetParamCellResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SoapstoneLib.Proto.Internal.Soapstone', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SoapstoneLib.Proto.Internal.Soapstone', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Soapstone:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SoapstoneLib.Proto.Internal.Soapstone/GetServerInfo',
            common__pb2.ServerInfoRequest.SerializeToString,
            common__pb2.ServerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SoapstoneLib.Proto.Internal.Soapstone/SearchObjects',
            internal__pb2.SearchObjectsRequest.SerializeToString,
            internal__pb2.SearchObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SoapstoneLib.Proto.Internal.Soapstone/GetObject',
            internal__pb2.GetObjectRequest.SerializeToString,
            internal__pb2.GetObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SoapstoneLib.Proto.Internal.Soapstone/BatchGetObjects',
            internal__pb2.BatchGetObjectsRequest.SerializeToString,
            internal__pb2.BatchGetObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SoapstoneLib.Proto.Internal.Soapstone/OpenResource',
            internal__pb2.OpenResourceRequest.SerializeToString,
            internal__pb2.OpenResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SoapstoneLib.Proto.Internal.Soapstone/OpenObject',
            internal__pb2.OpenObjectRequest.SerializeToString,
            internal__pb2.OpenObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SoapstoneLib.Proto.Internal.Soapstone/OpenSearch',
            internal__pb2.OpenSearchRequest.SerializeToString,
            internal__pb2.OpenSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteMassEdit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SoapstoneLib.Proto.Internal.Soapstone/ExecuteMassEdit',
            internal__pb2.ExecuteMassEditRequest.SerializeToString,
            internal__pb2.ExecuteMassEditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SoapstoneLib.Proto.Internal.Soapstone/ReloadParams',
            internal__pb2.ReloadParamsRequest.SerializeToString,
            internal__pb2.ReloadParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SoapstoneLib.Proto.Internal.Soapstone/ListParams',
            internal__pb2.ListParamsRequest.SerializeToString,
            internal__pb2.ListParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SoapstoneLib.Proto.Internal.Soapstone/DescribeParam',
            internal__pb2.DescribeParamRequest.SerializeToString,
            internal__pb2.DescribeParamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParamRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SoapstoneLib.Proto.Internal.Soapstone/GetParamRow',
            internal__pb2.GetParamRowRequest.SerializeToString,
            internal__pb2.GetParamRowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParamRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SoapstoneLib.Proto.Internal.Soapstone/GetParamRows',
            internal__pb2.GetParamRowsRequest.SerializeToString,
            internal__pb2.GetParamRowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListParamRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SoapstoneLib.Proto.Internal.Soapstone/ListParamRows',
            internal__pb2.ListParamRowsRequest.SerializeToString,
            internal__pb2.ListParamRowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetParamCell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SoapstoneLib.Proto.Internal.Soapstone/SetParamCell',
            internal__pb2.SetParamCellRequest.SerializeToString,
            internal__pb2.SetParamCellResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
